version: '2.1'

services:
  lulis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: lulis
    volumes:
      - ./tmp:/app/tmp
    environment:
      - LOG_LEVEL=debug
      - PORT=80
      - BASE_PATH=/app
      - FACE_VIDEO_URL="https://lulis.s3.amazonaws.com/33.mp4"
      - TWITCH_CHANNEL_NAME=${LULIS_TWITCH_CHANNEL_NAME}
      - TWITCH_STREAM_KEY=${LULIS_TWITCH_STREAM_KEY}
      - TWITCH_CLIENT_ID=${LULIS_TWITCH_CLIENT_ID}
      - OPEN_AI_KEY=${LULIS_OPEN_AI_KEY}
      - ELEVEN_LABS_KEY=${LULIS_ELEVEN_LABS_KEY}
      - ELEVEN_LABS_VOICE_ID=${LULIS_ELEVEN_LABS_VOICE_ID}
      - REPLICATE_KEY=${LULIS_REPLICATE_KEY}
      - AWS_BUCKET_NAME=${LULIS_AWS_BUCKET_NAME}
      - AWS_REGION=${LULIS_AWS_REGION}
      - AWS_ACCESS_KEY_ID=${LULIS_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${LULIS_AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_BASE_URL="https://lulis.s3.amazonaws.com/"